classdef appvar
    properties (Access = public)
        alpha_1
        alpha_2
        beta_1
        beta_2
        gamma_1
        gamma_2
        delta_1
        delta_2
        epsilon_1
        epsilon_2
        theta_1
        theta_2
        zeta_1
        zeta_2
        eta_1
        eta_2
        mu_1
        mu_2
        nu_1
        nu_2
        tau_1
        tau_2
        lambda_1
        lambda_2
        rho_1
        rho_2
        kappa_1
        kappa_2
        xi_1
        xi_2
        sigma_1
        sigma_2
        population
        initv1
        initv2
        initstate
        count=0
        omega_1
        omega_2
        color
        max_time
        ymax
        maxy
        cross
        cut=0
        block=[]
        te
        ba
        ga
        da
        rl
        kl
        xl
        sl
        db
        nm
        initpol
    end
end